package com.enumas.curconv.mvp.utils;

import java.util.HashMap;
import java.util.Map;

public class Constants {

    /**
     * Base currency (for now)
     * //TODO: if in time - move to model, make selectable through options
     */
    public static final String BASE_CURRENCY_CODE = "EUR";

    /**
     * Currency / country map.
     * //TODO: check if makes sense to move to csv, pass csv through config in settings
     */
    public static final Map<String, String> IATA_CURR_MAP = new HashMap<String, String>() {{
        put("USD","US");
        put("GBP","GB");
        put("EUR","EU");
        put("AUD","AU");
        put("XCD","AI");
        put("XOF","SN");
        put("XAF","CM");
        put("NZD","NZ");
        put("DKK","DK");
        put("XPF","PF");
        put("CHF","CH");
        put("ANG","BQ");
        put("WST","WS");
        put("STD","ST");
        put("SAR","SA");
        put("SCR","SC");
        put("SLL","SL");
        put("SGD","SG");
        put("SBD","SB");
        put("ZAR","ZA");
        put("LKR","LK");
        put("SRG","SR");
        put("SZL","SZ");
        put("SEK","SE");
        put("TWD","TW");
        put("TJS","TJ");
        put("TZS","TZ");
        put("THB","TH");
        put("TOP","TO");
        put("TTD","TT");
        put("TND","TN");
        put("TRY","TR");
        put("TMT","TM");
        put("UGX","UG");
        put("UAH","UA");
        put("AED","AE");
        put("UYU","UY");
        put("UZS","UZ");
        put("VUV","VU");
        put("VEB","VE");
        put("VND","VN");
        put("YER","YE");
        put("ZMK","ZM");
        put("ZWD","ZW");
        put("ARS","AR");
        put("AMD","AM");
        put("AWG","AW");
        put("DZD","DZ");
        put("AOA","AO");
        put("AZM","AZ");
        put("BSD","BS");
        put("BHD","BH");
        put("BDT","BD");
        put("BBD","BB");
        put("BYR","BY");
        put("BZD","BZ");
        put("BMD","BM");
        put("BTN","BT");
        put("BOB","BO");
        put("BAM","BA");
        put("BWP","BW");
        put("BRL","BR");
        put("BND","BN");
        put("BIF","BI");
        put("KHR","KH");
        put("CAD","CA");
        put("CVE","CV");
        put("KYD","KY");
        put("CLP","CL");
        put("RMB","CN");
        put("COP","CO");
        put("CDF","CD");
        put("CRC","CR");
        put("CZK","CZ");
        put("DJF","DJ");
        put("DOP","DO");
        put("EGP","EG");
        put("ERN","ER");
        put("ETB","ET");
        put("FJD","FJ");
        put("GMD","GM");
        put("GEL","GE");
        put("GHS","GH");
        put("GIP","GI");
        put("GTQ","GT");
        put("GNF","GN");
        put("GYD","GY");
        put("HTG","HT");
        put("HNL","HN");
        put("HKD","HK");
        put("HUF","HU");
        put("ISK","IS");
        put("INR","IN");
        put("IDR","ID");
        put("NID","IQ");
        put("ILS","IL");
        put("JMD","JM");
        put("JPY","JP");
        put("JOD","JO");
        put("KZT","KZ");
        put("KES","KE");
        put("KRW","KR");
        put("KWD","KW");
        put("KGS","KG");
        put("LAK","LA");
        put("LVL","LV");
        put("LBP","LB");
        put("LSL","LS");
        put("LRD","LR");
        put("LYD","LY");
        put("MOP","MO");
        put("MGA","MG");
        put("MWK","MW");
        put("MYR","MY");
        put("MVR","MV");
        put("MRO","MR");
        put("MUR","MU");
        put("MXN","MX");
        put("MDL","MD");
        put("MNT","MN");
        put("MAD","MA");
        put("MZM","MZ");
        put("NAD","NA");
        put("NPR","NP");
        put("NIO","NI");
        put("NGN","NG");
        put("NOK","NO");
        put("OMR","OM");
        put("PKR","PK");
        put("PAB","PA");
        put("PGK","PG");
        put("PYG","PY");
        put("PEN","PE");
        put("PHP","PH");
        put("PLN","PL");
        put("QAR","QA");
        put("ROL","RO");
        put("RUB","RU");
        put("RWF","RW");
    }};
}
